# ============================================================================
# FABRIKAGE.AUTOEXECUTION - AUTOMATISCHE AUSFÜHRUNG
# TOGETHERSYSTEMS. INTERNATIONAL TTT
# Industrielle Softwarefabrik - Pipelines, Generatoren, Auto-Fixes
# ============================================================================

version: "1.0.0"
name: "Fabrikage.AutoExecution"
description: "Automatische Produktionsketten, Generatoren, Pipelines"
status: "PERMANENT-ACTIVE"
mandatory: true

# ============================================================================
# A-START: ORDNER → ERKENNT → VALIDIERT → PRODUZIERT
# ============================================================================

a_start:
  entry_point: "bootstrap/a-start.ts"
  
  phases:
    - name: "recognize"
      description: "Erkennt Manifest, Profile, Toolchains"
      actions:
        - load_manifest
        - detect_toolchains
        - load_profiles
        - validate_schemas
    
    - name: "validate"
      description: "Validiert Policies, Schemata, Lizenzen"
      actions:
        - check_policies
        - validate_accessibility
        - validate_security
        - validate_quality
        - check_licenses
    
    - name: "produce"
      description: "Produziert Artefakte mit vollständiger Verifikation"
      actions:
        - generate_ui
        - generate_api
        - generate_adapters
        - build_artifacts
        - sign_artifacts
        - create_sbom

# ============================================================================
# GENERATOREN
# ============================================================================

generators:
  ui:
    path: "generators/ui/"
    features:
      - contrast_engine: true
      - accessibility_checks: true
      - responsive_design: true
      - component_library: true
    
  api:
    path: "generators/api/"
    features:
      - openapi_spec: true
      - validation: true
      - documentation: true
      - versioning: true
    
  adapters:
    path: "generators/adapters/"
    features:
      - device_protocols: true
      - protocol_profiles: true
      - error_handling: true
      - retry_logic: true

# ============================================================================
# PIPELINE-DAG
# ============================================================================

pipelines:
  build:
    path: "pipelines/build.yaml"
    stages:
      - validate
      - generate
      - build
      - test
      - scan
      - package
      - sign
  
  deploy:
    path: "pipelines/deploy.yaml"
    strategy: "blue-green"
    stages:
      - canary
      - staged_rollout
      - full_deployment
      - verify
  
  verify:
    path: "pipelines/verify.yaml"
    checks:
      - accessibility
      - security
      - performance
      - slo_compliance

# ============================================================================
# AUTO-FIXER
# ============================================================================

auto_fix:
  enabled: true
  policy_driven: true
  
  fixes:
    - name: "contrast_adjustment"
      policy: "policies/accessibility.yaml"
      allowed: true
      auto_apply: true
    
    - name: "aria_labels"
      policy: "policies/accessibility.yaml"
      allowed: true
      auto_apply: false  # Requires review
    
    - name: "lint_errors"
      policy: "policies/quality.yaml"
      allowed: true
      auto_apply: true
    
    - name: "security_vulnerabilities"
      policy: "policies/security.yaml"
      allowed: false  # Never auto-fix

# ============================================================================
# CACHE UND DETERMINISMUS
# ============================================================================

cache:
  enabled: true
  strategy: "hash_based"
  
  keys:
    - input_hash
    - toolchain_version
    - policy_version
  
  deterministic:
    enabled: true
    reproducible_builds: true
    hermetic_toolchains: true

# ============================================================================
# SELF-HEALING
# ============================================================================

self_healing:
  enabled: true
  
  actions:
    - trigger: "error_rate > 0.05"
      action: "rollback"
      cooldown: "5m"
    
    - trigger: "health_check_fail"
      action: "restart_service"
      cooldown: "1m"
    
    - trigger: "accessibility_regression"
      action: "block_deployment"
      cooldown: "0m"
    
    - trigger: "security_violation"
      action: "immediate_rollback"
      cooldown: "0m"

